# Usa imagem base oficial do Node.js
FROM node:20

# Define o diretório de trabalho no container
WORKDIR /app

# Copia os arquivos de dependências
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos do projeto
COPY . .

# Expõe a porta da aplicação, se necessário (ex: 3000)
EXPOSE 3000

# Comando para rodar a aplicação
CMD ["node", "index.js"]